/**
 * GitHub API helpers for creating child issues and linking sub-issues
 */

import type { Octokit } from "@octokit/rest";

interface CreateIssueParams {
  owner: string;
  repo: string;
  title: string;
  body: string;
  labels: string[];
}

interface LinkSubIssueParams {
  owner: string;
  repo: string;
  issueNumber: number;
  subIssueNumber: number;
}

interface SummaryParams {
  owner: string;
  repo: string;
  issueNumber: number;
  createdIssues: { number: number; title: string; url: string }[];
}

/**
 * Create a child issue via REST API
 */
export async function createChildIssue(
  octokit: Octokit,
  params: CreateIssueParams
): Promise<{ number: number; html_url: string }> {
  const { data } = await octokit.issues.create({
    owner: params.owner,
    repo: params.repo,
    title: params.title,
    body: params.body,
    labels: params.labels,
  });
  return { number: data.number, html_url: data.html_url };
}

/**
 * Link a child issue as a sub-issue of the parent using the sub_issues REST API
 */
export async function linkSubIssue(octokit: Octokit, params: LinkSubIssueParams): Promise<void> {
  // Use the sub_issues API to establish parent-child relationship
  await octokit.request("POST /repos/{owner}/{repo}/issues/{issue_number}/sub_issues", {
    owner: params.owner,
    repo: params.repo,
    issue_number: params.issueNumber,
    sub_issue_id: params.subIssueNumber,
  });
}

/**
 * Post a summary comment on the parent issue
 */
export async function postSummaryComment(octokit: Octokit, params: SummaryParams): Promise<void> {
  const { owner, repo, issueNumber, createdIssues } = params;

  if (createdIssues.length === 0) {
    await octokit.issues.createComment({
      owner,
      repo,
      issue_number: issueNumber,
      body: "⚠️ No child issues were created. Check the spec and try again.",
    });
    return;
  }

  const issueList = createdIssues.map((issue) => `- #${issue.number} — ${issue.title}`).join("\n");

  const body = [
    "## 📋 Plan Summary\n",
    `Created **${createdIssues.length}** child issue${createdIssues.length > 1 ? "s" : ""}:\n`,
    issueList,
    "\n---\n_Automatically generated by `/plan` command._",
  ].join("\n");

  await octokit.issues.createComment({
    owner,
    repo,
    issue_number: issueNumber,
    body,
  });
}

/**
 * Fetch available labels from the repository
 */
export async function getAvailableLabels(octokit: Octokit, owner: string, repo: string): Promise<string[]> {
  try {
    const { data } = await octokit.issues.listLabelsForRepo({
      owner,
      repo,
      per_page: 100,
    });
    return data.map((label) => label.name);
  } catch {
    return [];
  }
}
