import { Octokit } from "@octokit/rest";
import { PlanCommandInput, PlanResult, PluginConfig } from "./types";
import { createGitHubHelpers, GitHubHelpers } from "./github";
import { parseSpecToSubTasks, generateChildIssueBody, generatePlanSummary } from "./parser";

const DEFAULT_CONFIG: PluginConfig = {
  defaultPriority: "medium",
  autoAssign: true,
  labels: {
    priority: {
      high: "priority: high",
      medium: "priority: medium",
      low: "priority: low",
    },
    time: {
      "30m": "time: 30m",
      "1h": "time: 1h",
      "2h": "time: 2h",
      "4h": "time: 4h",
      "1d": "time: 1d",
      "2d": "time: 2d",
      "1w": "time: 1w",
    },
  },
};

/**
 * Main plugin handler for /plan command
 * Breaks an issue spec into child GitHub Issues
 */
export async function handlePlanCommand(
  octokit: Octokit,
  input: PlanCommandInput,
  config: Partial<PluginConfig> = {}
): Promise<PlanResult | null> {
  const mergedConfig = { ...DEFAULT_CONFIG, ...config };
  const github = createGitHubHelpers(octokit);
  const { owner, repo, issueNumber, issueBody, issueTitle } = input;

  // Check if the command was invoked
  if (!issueBody?.includes("/plan")) {
    return null;
  }

  // Check if already planned (avoid duplicates)
  if (issueBody.includes("> Generated by `/plan` command plugin")) {
    await github.addComment(
      owner,
      repo,
      issueNumber,
      "⚠️ This issue has already been planned. Please check for existing child issues."
    );
    return null;
  }

  // Parse the spec into subtasks
  const tasks = parseSpecToSubTasks(issueBody);

  if (tasks.length === 0) {
    await github.addComment(
      owner,
      repo,
      issueNumber,
      "⚠️ Could not extract subtasks from the issue body. Please ensure the spec contains:\n" +
        "- Markdown sections (## Task Name), or\n" +
        "- Checkbox lists (- [ ] Task description)"
    );
    return null;
  }

  // Add a comment to indicate planning has started
  await github.addComment(
    owner,
    repo,
    issueNumber,
    `🔄 Planning started... Breaking down issue into ${tasks.length} sub-tasks.`
  );

  const createdIssues: { issueNumber: number; title: string }[] = [];

  // Create child issues
  for (const task of tasks) {
    const labels: string[] = [];

    // Add priority label
    if (task.priority && mergedConfig.labels?.priority[task.priority]) {
      labels.push(mergedConfig.labels.priority[task.priority]);
    }

    // Add time estimate label
    if (task.timeEstimate && mergedConfig.labels?.time[task.timeEstimate]) {
      labels.push(mergedConfig.labels.time[task.timeEstimate]);
    }

    // Add "sub-task" label
    labels.push("sub-task");

    // Generate child issue body
    const childBody = generateChildIssueBody(issueNumber, repo, owner, task);

    try {
      const childIssueNumber = await github.createIssue(
        owner,
        repo,
        task.title,
        childBody,
        labels
      );

      createdIssues.push({
        issueNumber: childIssueNumber,
        title: task.title,
      });

      // Link sub-issue to parent (if API supports it)
      try {
        await github.linkSubIssue(owner, repo, issueNumber, childIssueNumber);
      } catch {
        // sub_issues API may not be available, continue anyway
      }
    } catch (error) {
      console.error(`Failed to create child issue for task: ${task.title}`, error);
    }
  }

  // Post plan summary
  if (createdIssues.length > 0) {
    const summary = generatePlanSummary(issueNumber, tasks, createdIssues);
    await github.addComment(owner, repo, issueNumber, summary);
  }

  return {
    parentIssueNumber: issueNumber,
    childIssues: createdIssues.map((issue, i) => ({
      ...issue,
      priority: tasks[i]?.priority,
      timeEstimate: tasks[i]?.timeEstimate,
    })),
  };
}

/**
 * Plugin entry point - listens for issue comments
 */
export async function pluginEntry(octokit: Octokit, payload: any) {
  const comment = payload.comment;
  if (!comment || !comment.body?.includes("/plan")) {
    return;
  }

  const issue = payload.issue;
  if (!issue) {
    return;
  }

  const [owner, repo] = payload.repository.full_name.split("/");

  await handlePlanCommand(octokit, {
    owner,
    repo,
    issueNumber: issue.number,
    issueBody: issue.body || "",
    issueTitle: issue.title,
  });
}

export { DEFAULT_CONFIG };
export type { PlanCommandInput, PlanResult, PluginConfig, SubTask } from "./types";
