import { SubTask } from "./types";

/**
 * Parses an issue spec body and extracts subtasks
 * Looks for markdown patterns like:
 * - `## Task Name` sections
 * - Checkbox lists `- [ ] Task description`
 * - Numbered lists with time estimates
 */
export function parseSpecToSubTasks(body: string): SubTask[] {
  const tasks: SubTask[] = [];

  // Split by markdown headers (## or ###)
  const sections = body.split(/^##+\s+/m).slice(1);

  for (const section of sections) {
    const lines = section.split("\n");
    const title = lines[0]?.trim();
    if (!title || title.toLowerCase().includes("usage") || title.toLowerCase().includes("files")) {
      continue;
    }

    // Extract time estimate if present (e.g., "2h", "1d", "30m")
    const timeMatch = title.match(/(\d+[hmd])/i);
    const timeEstimate = timeMatch ? timeMatch[1] : undefined;

    // Clean title
    const cleanTitle = title.replace(/\s*\d+[hmd]\s*$/i, "").trim();

    // Extract description from remaining lines
    const description = lines
      .slice(1)
      .filter((line) => line.trim() && !line.startsWith("```"))
      .join("\n")
      .trim();

    // Determine priority based on keywords
    let priority: SubTask["priority"];
    const lowerTitle = cleanTitle.toLowerCase();
    if (lowerTitle.includes("critical") || lowerTitle.includes("urgent") || lowerTitle.includes("core")) {
      priority = "high";
    } else if (lowerTitle.includes("nice to have") || lowerTitle.includes("optional")) {
      priority = "low";
    } else {
      priority = "medium";
    }

    tasks.push({
      title: cleanTitle || "Unnamed Task",
      description: description || `Implement ${cleanTitle}`,
      priority,
      timeEstimate,
    });
  }

  // Fallback: if no sections found, try checkbox list
  if (tasks.length === 0) {
    const checkboxes = body.match(/- \[ \]\s+(.+)/g);
    if (checkboxes) {
      for (const cb of checkboxes) {
        const text = cb.replace("- [ ] ", "").trim();
        const timeMatch = text.match(/(\d+[hmd])/i);
        tasks.push({
          title: text.replace(/\s*\d+[hmd]\s*$/i, "").trim(),
          description: text,
          priority: "medium",
          timeEstimate: timeMatch ? timeMatch[1] : undefined,
        });
      }
    }
  }

  return tasks;
}

/**
 * Generates a child issue body with reference to parent
 */
export function generateChildIssueBody(
  parentIssueNumber: number,
  parentRepo: string,
  parentOwner: string,
  task: SubTask
): string {
  return `## Task Description

${task.description}

${task.priority ? `**Priority:** ${task.priority}` : ""}
${task.timeEstimate ? `**Estimated Time:** ${task.timeEstimate}` : ""}

---

**Parent Issue:** #${parentIssueNumber}
**Repository:** ${parentOwner}/${parentRepo}

> This issue was auto-generated by the \`/plan\` command.
`;
}

/**
 * Generates the plan summary comment
 */
export function generatePlanSummary(
  parentIssueNumber: number,
  tasks: SubTask[],
  createdIssues: { issueNumber: number; title: string }[]
): string {
  const taskList = createdIssues
    .map(
      (issue, i) =>
        `- [ ] #${issue.issueNumber} — **${issue.title}**`
    )
    .join("\n");

  return `## 📋 Plan Execution Complete

Successfully broke down issue #${parentIssueNumber} into **${createdIssues.length} sub-tasks**:

${taskList}

---

> Generated by \`/plan\` command plugin
`;
}
